## Synthetic population pipeline for Île-de-France
## based on the synpp package

# This is the path to a directory where the pipeline can store temporary data
working_directory: ../cache

# This section defines which parts of the pipeline should be run
run:
  - synthesis.output # To create the output population in the output_path (see below)
  - matsim.simulation.full_run # Uncomment, if you want to run the full simulation (you'll need Java for that)
  - analysis.synthesis.population

# Here the configuraiton of the pipeline starts
config:

  ##############################
  # Some general configuration #
  ##############################

  ## Number of CPUs to use
  processes: 4

  ################
  # Random seeds #
  ################

  ## global random seed for the output population
  random_seed: 1234

  ##################################################
  # Define sampling rate for the output population #
  ##################################################

  sampling_rate: 0.11

  #################################
  # household travel survey (HTS) #
  #################################

  ## Define whether to use ENTD or EGT as the HTS
  hts: emp 
  ## Whether to filter people going outside of the area and other filters
  filter_hts: false

  ##################
  # Zone selection #
  ##################

  ## select regions by region_id
  regions: []

  ## select departments by department_id
  departments: [17]

  #######################
  #     Output paths    #
  #######################

  ## output folder
  output_path: ../output
  ## output prefix, appended to file names
  output_prefix: 17_

  ##############################
  #  Algorithms configurations #
  ##############################

  ## Use the bhepop2 package for attributing income
  income_assignation_method: bhepop2 # uniform, bhepop2

  ## Activate if you want to run mode choice, will assign a mode to output trips
  mode_choice: true

  ## Exclude entreprise without any employee (trancheEffectifsEtablissement is NA, "NN" or "00")
  exclude_no_employee: true

  ## source for the education locations
  education_location_source: weighted # bpe, addresses
  home_location_source: addresses # "addresses", "buildings", "tiles"

  ## When running matsim

  ## performing one run of the matsim simulation or not
  run_matsim: true

  ## creating the far or not
  write_jar: true

  ## Cutter settings: Used to define a specific area for analysis or simulation
  # cutter:

    ## Path to the directory containing the cutter geojson file
    # path: cutter

    ## Name of the cutter file (e.g., GeoJSON file defining the area)
    # file: cutter.geojson

    ## Name of the cutter (used for output file naming)
    # name: paris

    ## Whether to apply the cutter after the full simulation (True/False)
    # after_full_simulation: True

  ## NoiseModelling settings: Configuration for noise exposure or noise map generation
  # noise:

    ## Type of noise computation to perform ("exposure" for exposure analysis, "maps" for noise maps)
    # compute: exposure

    ## Size of the time bins for noise computation, in seconds (e.g., 3600 for hourly bins)
    # time_bin_size: 3600

    ## Start time for noise computation, in seconds (e.g., 0 for midnight)
    # time_bin_min: 0

    ## End time for noise computation, in seconds (e.g., 86400 for 24 hours)
    # time_bin_max: 86400

    ## Maximum order of reflections to consider (e.g., 1 for first-order reflections)
    # refl_order: 1

    ## Maximum distance for considering noise sources, in meters
    # max_src_dist: 750

    ## Maximum distance for considering reflections, in meters
    # max_refl_dist: 50

  ############################
  #  Analysis configuration  #
  ############################

  ## Whether to use previously generated files or not
  # analysis_from_file: false

  ## prefix of the files to compare to
  # comparison_file_prefix: other_

  ##########################
  #  Tools configuration   #
  ##########################

  ## Mostly interesting if you run the simulation, or you activate the `mode_choice` option,

  ## Binaries paths
  # git_binary: git
  # java_binary: java
  # maven_binary: mvn
  # maven_local_cache: false

  ## Binaries parameters
  java_memory: 14G
  # maven_skip_tests: false

  ## eqasim-java parameters
  # eqasim_version: 1.5.0
  # eqasim_branch: develop
  # eqasim_commit: ece4932
  # eqasim_repository: https://github.com/eqasim-org/eqasim-java.git
  # eqasim_path: ""
  # eqasim_tag:


  ## pt2matsim parameters
  # pt2matsim_version: 22.3
  # pt2matsim_branch: v22.3

  ## Strategy to use in pt2matsim gtfs processing
  # gtfs_date: dayWithMostServices

  ## Export the detailed geometry of the network before simplification in pt2matsim
  # export_detailed_network: true

  #################
  #  Input paths  #
  #################

  ## Absolute root path of all input data
  data_path: ../data
  ban_path: ban_17
  bdtopo_path: bdtopo_17
  gtfs_path: gtfs_17
  osm_path: osm_17

  # vehicles_method: default # fleet_sample, default
  # critair_path: critair
  # 2rm_path: vehicles
  # vehicles_year: 2021
  # with_motorcycles: false
